version: "3"
services:
  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - ../..:/app
    working_dir: /app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_REGION: ${AWS_DEFAULT_REGION}
    command: bash ./tasks/ci/build
  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    volumes:
      - ../..:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    command: bash ./tasks/ci/deploy
